### ISSUE TITLE
MEMCACHED_NOTFOUND for the key "shortcut-0"

### ISSUE THREAD

**Issue by SeKwonLee** [WukLab/pDPM#1]
I am trying to run Clover to test it on three ib-enabled cloud machines. However, the metadata server (Memcached) keeps returning "MEMCACHED_NOTFOUND" error in getting the key "shortcut-0", thereby CN is blocked after calling the function "client_get_shortcut". Could you tell me about the possible issues and solutions?

I configured and ran experiments by following the instructions specified in [the document](https://github.com/WukLab/pDPM/blob/master/Documentation/clover.md). 1MS, 1CN, and 1MN were separately executed in three physical machines respectively. I only modified `RSEC_NETWORK_MODE` macro to be `RSEC_NETWORK_IB` from the original source codes and changed `MEMCACHED_SERVER_IP` in `run_memory.sh` and `run_client.sh`.

The hardware specs I am using are specified below.
RNIC: Mellanox Technologies MT27500 Family [ConnectX-3]
CPU: Intel Xeon CPU E5-2670 v3 @ 2.30 GHz
DRAM: 128GB

Thanks in advance.

**Comment by shinyehtsai** [comment]
Hello SeKwon, 
Thank you for your interest of using Clover. Did you install Memcached on metadata server? If you use IP on Mellanox Cx3, it also need to make sure that IPoIB is configured correctly. You can check the connectivity around this part of code, https://github.com/WukLab/pDPM/blob/82f3c98e18938b7c7fdba8dfe062052ccd3634f5/clover/memcached.cc#L1-L20

**Comment by SeKwonLee** [comment]
Hi @shinyehtsai,

Thanks for your quick response.

1. Did you install Memcached on metadata server?
Yes

2. If you use IP on Mellanox Cx3, it also needs to make sure that IPoIB is configured correctly.
I configured IPoIB in every machine and made MN & CN use the IP (MS) assigned for IPoIB for memcached server ip. 

3. Check connectivity.
I have confirmed the connectivity by checking CN can receive the values for the keys "machine-rc-\*" and "machine-ud-\*" from MS. However, the get request by CN for the key "shortcut-0" returns MEMCACHED_NOTFOUND error which is returned when the given key is not found from Memcached server.


When I briefly looked into the steps of initializing CN, the implementation seems to request the information of shortcuts before inserting some amount of keys. However, from my understanding, the shortcuts would be produced after CN executes key insertions. Shouldn't CN first execute the insertions (for warming up the key-value store) before requesting shortcut information to MS?

**Comment by shinyehtsai** [comment]
Shortcut should be inserted in this place, https://github.com/WukLab/pDPM/blob/c2a2489e6ccddd313fd29cd641948a0784e678c1/clover/memory.cc#L91-L94.
Could you check the connectivity between memory and memcached?

**Comment by SeKwonLee** [comment]
@shinyehtsai,

I have confirmed MN and MS are connected well. However, when I checked the key used for MN to publish initial shortcuts to MS and compared it with the one by CN, they were different. Note that I used unique node ID 0, 1, 2 for MS, MN, and CN respectively as specified in the document.

- Key used by MN (memcached_set): `shortcut--1`
- Key used by CN (memcached_get): `shortcut-0`

Could you check it once to identify whether this is caused by implementations or configurations?

**Comment by shinyehtsai** [comment]
Could you try this commend instead?
S0: memcached -u root -I 128m -m 2048
S0: ./run_ms.sh 0
S1: ./run_clients.sh 1
S2: ./run_memory.sh 2
I somehow remember the ID of MN should be after CN.

**Comment by SeKwonLee** [comment]
After changing unique numbers, it works now. Thanks for your help. I will close this issue.
