### ISSUE TITLE
Run experiments using larger dataset

### ISSUE THREAD

**Issue by SeKwonLee** [WukLab/pDPM#5]
Hi,

I am trying to run the ycsb experiments using larger datasets per thread than the provided example. From my understanding, the provided example seems to assign 1million keys per thread. However, I would like to run experiments using larger datasets such as 30 million keys (with 32-byte value per key). To run this experiment, I launched 1MN, 1CN, and 1MS from separate physical machines and assigned 30million prepopulated keys to each thread in the CN (Since I am using 8threads in the CN, each thread will take around 3.75 million keys to insert). To run this experiment, I thought `MITSUME_MAX_KEYS` should be changed to be larger than the current configuration (100K). I am understanding this parameter should be configured to be the larger number than the maximum dataset, thus should be changed to be over 30million (Could you check if my understanding is correct?). After this configuration, I tested the experiment but observed a failure (the CN was blocked after making the error message below) after allocating 2,012,928 objects using `mitsume_tool_open`. Could you check if there's anything I am missing and give me some advice to run larger datasets?

```
[INFO] mitsume_clt_consumer_get_entry_from_list:94 : ask for size:128 rep:0 too many times
```

Thanks in advance.

**Comment by shinyehtsai** [comment]
Hello Sekwon,

Please update https://github.com/WukLab/pDPM/blob/master/clover/mitsume_con_alloc.cc#L10-L17 accordingly to get more size:128 entries. This should be able to unblock failed to get entry error.

**Comment by SeKwonLee** [comment]
Hi @shinyehtsai ,

Thanks for your quick response. The error has been solved after the update. I will close this issue.
