### ISSUE TITLE
Errors while execute run_clients.sh

### ISSUE THREAD

**Issue by prokey2001** [WukLab/pDPM#6]
Hi! When I execute "run_clients.sh 1", it reported an error,the screenshot is as follows
![image](https://user-images.githubusercontent.com/93810132/200733668-1c7d8dbb-7217-42ac-84b5-b4d76387d3d4.png)
I have two ib network cards, mlx_ 0 and mlx_ 1. I want touse mlx_ 1, but it runs in mlx_0 default, I modified ibdev_ ID, but still running in mlx_ 0. I think the error is probably due to the wrong network card. Could you give me some help? Thank you very much!

**Comment by prokey2001** [comment]
![image](https://user-images.githubusercontent.com/93810132/200736308-36265137-6d3a-470b-b0d8-7592d2182b71.png)
Hi！It seems that the sh file has some errors. It should be -- device id instead of --device-id.After I modify it, I can successfully switch the network card.

**Comment by prokey2001** [comment]
Hello, when I execute the clover system, the following error will be displayed
![image](https://user-images.githubusercontent.com/93810132/201105969-a3175765-30fb-466a-83cc-33520ec3c96b.png)
The RoCE mode is used, and the network card settings are correctly specified. Could you give me some help? Thank you very much

**Comment by Dicridon** [comment]
If you are running RoCE, please make sure the current GID index is selected. You can modify the macro `RSEC_SGID_INDEX` defined in file `ibsetup.h`. The correct gid index can be found by `show_gids`.
